repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        stages: [pre-commit]
    -   id: end-of-file-fixer
        stages: [pre-commit]
    -   id: check-yaml
        stages: [pre-commit]
    -   id: check-added-large-files
        stages: [pre-commit]
        args: ['--maxkb=10240']
    -   id: check-ast
        stages: [pre-commit]
    -   id: check-json
        stages: [pre-commit]
    -   id: check-merge-conflict
        stages: [pre-commit]
    -   id: detect-private-key
        stages: [pre-commit]
