name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -e ".[dev]"
      - name: Run pre-commit
        run: |
          # Ensure pre-commit is in PATH
          export PATH="$HOME/.local/bin:$PATH"
          # Install pre-commit hooks
          pre-commit install
          # Run pre-commit on all files
          pre-commit run --all-files
      - name: Run tests
        run: |
          python -m pytest tests/
      - name: Build documentation
        run: |
          mkdocs build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m semantic_release publish
